[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"

[project]
name = "python-apprentice"
version = "0.1.0"
description = "Exercises and projects from my Python apprenticeship program."
authors = [
  { name = "IceBox" }
]
readme = "README.md"
requires-python = ">=3.11"
dependencies = []

[project.urls]
Repository = "https://github.com/arionvlad/python-apprentice"

[tool.setuptools.packages.find]
where = ["src"]