[build-system]
requires = ["setuptools>=65.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "python-apprentice"
version = "0.1.0"
description = "A minimal Python package template."
authors = [
  { name = "IceBox" }
]
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
]
dependencies = []

[project.optional-dependencies]
test = ["pytest>=7.0"]

[tool.setuptools]
packages = ["app"]
package-dir = {"" = "src"}

[tool.setuptools.package-data]
"app" = ["py.typed"]
